"""add reviews table

Revision ID: 25e31858dbb2
Revises: ebc0d6244061
Create Date: 2025-12-30 17:56:58.019163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25e31858dbb2'
down_revision: Union[str, None] = 'ebc0d6244061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False, comment='Hostaway review ID'),
    sa.Column('listing_id', sa.Integer(), nullable=False, comment='Property/listing ID'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Channel ID (2018=Airbnb, 2005=Booking.com, 2022=Google)'),
    sa.Column('guest_name', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False, comment='Rating 1-5 or 1-10, normalized'),
    sa.Column('public_review', sa.Text(), nullable=True, comment='Review text content'),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False, comment='When review was submitted'),
    sa.Column('status', sa.String(length=32), nullable=False, comment="e.g., 'published', 'pending'"),
    sa.Column('type', sa.String(length=32), nullable=False, comment="e.g., 'guest-to-host'"),
    sa.Column('is_displayed', sa.Boolean(), nullable=False, comment='Show on public site'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Original API payload'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_reviews_channel_id', 'reviews', ['channel_id'], unique=False)
    op.create_index('ix_reviews_is_displayed', 'reviews', ['is_displayed'], unique=False)
    op.create_index('ix_reviews_listing_id', 'reviews', ['listing_id'], unique=False)
    op.create_index('ix_reviews_rating', 'reviews', ['rating'], unique=False)
    op.create_index('ix_reviews_submitted_at', 'reviews', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_submitted_at', table_name='reviews')
    op.drop_index('ix_reviews_rating', table_name='reviews')
    op.drop_index('ix_reviews_listing_id', table_name='reviews')
    op.drop_index('ix_reviews_is_displayed', table_name='reviews')
    op.drop_index('ix_reviews_channel_id', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
